### ISSUE TITLE
Coffeelint support for server code in brunch?

### ISSUE THREAD

**Issue by gcatto** [brunch/coffeelint-brunch#13]
I use brunch for both my client and server code. I would like to run coffeelint-brunch against both, but if I update coffeelint.pattern to include my server directory, it only works if I also add my server directory to paths.watched (which I believe is the wrong way to go). Is there a way to do this?

**Comment by paulmillr** [comment]
not yet i'm afraid. brunch is mostly client-side now.

**Comment by gcatto** [comment]
Thought that would be the case, but figured I'd ask. Thanks!
