### ISSUE TITLE
Broken pattern

### ISSUE THREAD

**Issue by urosgruber** [brunch/coffeelint-brunch#18]
After investigation why Coffee linter stopped throwing warnings I noticed that pattern is broken. Looks like bug introduced during interface upgrade to 2.0. #17 fix this.

**Comment by shvaikalesh** [comment]
Thanks for the PR!

**Comment by urosgruber** [comment]
Can you please re-publish this last changes to npm. npm install still downloads broken version.

**Comment by paulmillr** [comment]
@urosgruber done
